#!/usr/bin/env fish

function header_banner -a title
    set title_length (math (string length $title) + 4)
    set stars (string repeat -n $title_length '*')
    set_color brblue
    echo
    echo $stars
    echo "* $title *"
    echo $stars
    set_color normal
end

function setup_fish_vendor
    # fish plugins I use are included verbatim in .config/fish/vendor
    # they must be copied to .config/fish to become usable
    header_banner "Setting up fish vendored plugins"

    # disable fzf plugin on slow systems
    if test "$disable_fzf" = true
        echo "Disabling fzf-fish plugin"
        rm -rf $HOME/.config/fish/conf.d/fzf.fish $HOME/.config/fish/vendor/fzf-fish
    end
    cp -prf $HOME/.config/fish/vendor/* $HOME/.config/fish/
    or exit 2
    rm -rf $HOME/.config/fish/vendor/
end

function set_fish_universal_vars
    header_banner "Setting fish universal variables"

    echo "Unsetting fish_greeting"
    set -U fish_greeting

    set enabled_features ampersand-nobg-in-token,qmark-noglob,regex-easyesc,stderr-nocaret
    echo "Enabling fish_features:" $enabled_features
    set -U fish_features $enabled_features

    echo "Enabling pure prompt show root prefix"
    set -U pure_show_prefix_root_prompt true

    echo "Enabling pure prompt show error code in prompt"
    set -U pure_separate_prompt_on_error true
end

function set_default_shell
    header_banner "Set fish as default shell"
    set current_default_shell (getent passwd $LOGNAME | cut -d: -f7)
    if test $current_default_shell != /usr/bin/fish
        echo "Setting /usr/bin/fish as default shell, enter password to confirm"
        chsh -s /usr/bin/fish
    else
        echo "fish is already the default shell, nothing to do."
    end
end

function setup_emacs
    header_banner "Set up Emacs configuration"
    if type -q emacs
        echo Emacs installation found at (which emacs), version (emacs --version)[1]
        if test -e $HOME/.emacs.d
            echo "Emacs config already found at $HOME/.emacs.d, skipping further configuration"
        else
            set repo https://github.com/haplo/dotemacs
            set target $HOME/.emacs.d
            echo "Downloading Emacs config from $repo to $target"
            git clone $repo $target
        end
    else
        echo "No Emacs installation detected, skipping Emacs configuration"
    end
end

setup_fish_vendor
set_fish_universal_vars
set_default_shell
if type -q emacs
    setup_emacs
end
