[*]
host=127.0.0.1
port=9931
n-gpu-layers = 99
flash-attn = 1

[Qwen3.8-27b]
hf=unsloth/Qwen3.8-27B-GGUF:Q4_K_M
fa=1
#ctx-size=131072
ctx-size=98304
ctk=q8_0
ctv=q8_0
spec-type=draft-mtp
spec-draft-n-max=4
spec-draft-n-min=1
spec-draft-p-min=0.75
b=2048
ub=512
temp=1.0
top-p=0.95
top-k=20
min-p=0.0
presence-penalty=1.5
repeat-penalty=1.0
alias=qwen27b